# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
