# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(default='admin_app/img/img.jpg', upload_to='apps/ecommerce/static/ecommerce/img'),
        ),
    ]
