# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20161221_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.09, max_digits=2, null=True),
        ),
    ]
