# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20161221_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(default='admin_app/img/img.jpg', upload_to='ecommerce/img'),
        ),
    ]
