# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_merge_20161222_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Order in Process', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
